#!/usr/bin/env python3
"""
Pull GREEN-coloured events (matches / fixtures / shoots) from Google
Calendar and write data/calendar.json.

Nick colour-codes everything he's shooting as green (Basil = colorId 10;
Sage = colorId 2). Only the Calendar API returns colour, so this uses a
Google service account (an .ics feed can't filter by colour).

Env / GitHub secrets:
  GOOGLE_SERVICE_ACCOUNT_JSON   full service-account key JSON (as a string)
  CALENDAR_IDS                  optional, comma-separated calendar IDs to scan
                                (default: the primary calendar below)

Setup once: share each calendar with the service account's email
(Calendar settings → "Share with specific people" → Reader access).

Local test:
  export GOOGLE_SERVICE_ACCOUNT_JSON="$(cat key.json)"
  python scripts/sync_calendar.py
"""
import os, json, sys, datetime, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

# Green colour IDs that mean "I'm shooting this": 10 = Basil, 2 = Sage.
MATCH_COLOR_IDS = {"10", "2"}
DEFAULT_CALENDARS = ["falzonnicholas01@gmail.com"]
LOOKAHEAD_DAYS = 150

# Keep the feed to real fixtures/one-offs. Recurring green events (e.g. the
# weekly Imperial Band Practice) and obvious practice/rehearsal titles are skipped.
SKIP_RECURRING = True
SKIP_TITLE_KEYWORDS = ("band practice", "rehearsal")


def main():
    raw = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON")
    if not raw:
        print("Missing GOOGLE_SERVICE_ACCOUNT_JSON — skipping calendar sync.", file=sys.stderr)
        return 0

    from google.oauth2 import service_account
    from googleapiclient.discovery import build

    info = json.loads(raw)
    creds = service_account.Credentials.from_service_account_info(
        info, scopes=["https://www.googleapis.com/auth/calendar.readonly"])
    svc = build("calendar", "v3", credentials=creds, cache_discovery=False)

    cal_ids = [c.strip() for c in os.environ.get(
        "CALENDAR_IDS", ",".join(DEFAULT_CALENDARS)).split(",") if c.strip()]

    now = datetime.datetime.now(datetime.timezone.utc)
    time_min = now.isoformat()
    time_max = (now + datetime.timedelta(days=LOOKAHEAD_DAYS)).isoformat()

    matches = []
    for cal_id in cal_ids:
        page = None
        while True:
            resp = svc.events().list(
                calendarId=cal_id, timeMin=time_min, timeMax=time_max,
                singleEvents=True, orderBy="startTime", maxResults=250,
                pageToken=page).execute()
            for e in resp.get("items", []):
                if e.get("colorId") not in MATCH_COLOR_IDS:
                    continue
                if SKIP_RECURRING and e.get("recurringEventId"):
                    continue  # drop weekly practices etc.
                title_l = (e.get("summary") or "").lower()
                if any(k in title_l for k in SKIP_TITLE_KEYWORDS):
                    continue
                start = e.get("start", {})
                end = e.get("end", {})
                all_day = "date" in start
                matches.append({
                    "title": e.get("summary", "(untitled)"),
                    "start": start.get("dateTime") or start.get("date"),
                    "end": end.get("dateTime") or end.get("date"),
                    "allDay": all_day,
                    "location": e.get("location", ""),
                    "calendar": resp.get("summary", cal_id),
                    "colorId": e.get("colorId"),
                    "link": e.get("htmlLink", ""),
                })
            page = resp.get("nextPageToken")
            if not page:
                break

    matches.sort(key=lambda m: m["start"])

    (DATA / "calendar.json").write_text(json.dumps({
        "_note": "Auto-generated by sync_calendar.py — green events from Google Calendar.",
        "updated": now.isoformat().replace("+00:00", "Z"),
        "matches": matches,
    }, indent=2))
    print(f"calendar.json updated: {len(matches)} green events across {len(cal_ids)} calendar(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
